%% Table 1 synthetic comparison based on the user's AC^2-TRPCA code
% Compared methods:
%   1) LRTV
%   2) ATNN
%   3) CCSVS
%   4) AC^2-TRPCA
%
% IMPORTANT:
% It does not intentionally weaken any competing method. For every configuration, all competing methods receive
% exactly the same L0, E0, and Y = L0 + E0.
%
% The rank generated by this script is the rank of the mode-3 subspace:
%       rank(L0_(3)) = r3,
% because L0 = B0 x_3 D0 and D0 has r3 columns.


clear;
clc;
close all;

rng(42);

%% ==================== Paths ====================
scriptDir = fileparts(mfilename('fullpath'));
if ~isempty(scriptDir)
    cd(scriptDir);
end

addpath(genpath(fullfile(scriptDir, 'lib')));
addpath(genpath(fullfile(scriptDir, 'utils')));

algorithmRoot = fullfile(scriptDir, 'RPCA_Code');
LRTVRoot = fullfile(scriptDir, 'RPCA_Code', 'TRPCA', 'LRTV');

if isfolder(algorithmRoot)
    addpath(genpath(algorithmRoot));
else
    warning('Algorithm folder not found: %s', algorithmRoot);
end

if isfolder(LRTVRoot)
    addpath(genpath(LRTVRoot));
else
    warning('LRTV folder not found: %s', LRTVRoot);
end

addpath(scriptDir);

requiredFunctions = { ...
    'ATNN_RPCA_unifiedstop', ...
    'trpca_tnn', ...
    'LRTV_accelerate'};

for q = 1:numel(requiredFunctions)
    assert(exist(requiredFunctions{q}, 'file') == 2, ...
        'Missing required function: %s', requiredFunctions{q});
end

%% ==================== Experiment settings ====================
n_list = [100, 200];

% Each row is [rank ratio, sparse ratio].
configs = [ ...
    0.05, 0.05; ...
    0.05, 0.10; ...
    0.10, 0.10; ...
    0.10, 0.20  ...
];

% Three independent trials reduce runtime while retaining a basic
% stability check. Use five trials when computational resources permit.
numTrials = 1;

baseSeed = 42;

% Numerical reporting thresholds.
rankTol = 1e-4;
sparseTol = 1e-4;
successTol = 1e-3;

methodNames = { ...
    'LRTV'; ...
    'ATNN'; ...
    'CCSVS'; ...
    'AC^2-TRPCA'};

numMethods = numel(methodNames);
numCases = numel(n_list) * size(configs,1);

%% ==================== Output folder ====================
saveRoad = fullfile(scriptDir, 'results', ...
    'Synthetic_Comparison_Compact_Fair');

if ~exist(saveRoad, 'dir')
    mkdir(saveRoad);
end

%% ==================== Allocate arrays ====================
% Dimensions: method x case x trial
ErrL = nan(numMethods, numCases, numTrials);
ErrE = nan(numMethods, numCases, numTrials);
EstimatedTubalRank = nan(numMethods, numCases, numTrials);
EstimatedMode3Rank = nan(numMethods, numCases, numTrials);
EstimatedSparsity = nan(numMethods, numCases, numTrials);
Runtime = nan(numMethods, numCases, numTrials);
Iterations = nan(numMethods, numCases, numTrials);
Success = false(numMethods, numCases, numTrials);

CaseN = nan(numCases,1);
CaseR3 = nan(numCases,1);
CaseSparseRatio = nan(numCases,1);
CaseTrueSparsity = nan(numCases,1);

fprintf('Starting synthetic comparison based on the original Table-1 code...\n');

%% ==================== Main experiment ====================
caseIdx = 0;

for nIdx = 1:numel(n_list)

    n = n_list(nIdx);

    for cfgIdx = 1:size(configs,1)

        caseIdx = caseIdx + 1;

        rankRatio = configs(cfgIdx,1);
        sparseRatio = configs(cfgIdx,2);

        trueRank = round(rankRatio * n);
        r3 = trueRank;
        m = round(sparseRatio * n^3);

        CaseN(caseIdx) = n;
        CaseR3(caseIdx) = r3;
        CaseSparseRatio(caseIdx) = sparseRatio;
        CaseTrueSparsity(caseIdx) = m;

        fprintf('\n============================================================\n');
        fprintf(['Case %d/%d: n=%d, r3=%d, sparse ratio=%.2f, ', ...
            '||E0||_0=%d\n'], ...
            caseIdx, numCases, n, r3, sparseRatio, m);
        fprintf('============================================================\n');

        for trial = 1:numTrials

            seed = baseSeed + 1000 * caseIdx + trial;
            rng(seed, 'twister');

            %% ---------- Fair joint low-rank data generation ----------
            % The clean tensor is constructed so that it satisfies both
            % rank_t(L0)=trueRank and rank(L0_(3))=r3.
            [L0,B0,D0] = generate_joint_lowrank_tensor( ...
                n,r3,trueRank);

            % Match the signal scale to the +/-1 sparse corruption.
            signalStd = std(L0(:));
            L0 = L0 / max(signalStd,eps);
            B0 = B0 / max(signalStd,eps);

            E0 = zeros(n, n, n);
            index = randperm(n^3, m);
            E0(index) = sign(randn(m,1));

            Y = L0 + E0;

            trueTubalRank = numerical_tubal_rank(L0,rankTol);
            trueMode3Rank = numerical_mode3_rank(L0,rankTol);

            fprintf(['Trial %d/%d, seed=%d, ', ...
                'verified tubal rank=%d (target=%d), ', ...
                'mode-3 rank=%d (target=%d)\n'], ...
                trial,numTrials,seed,trueTubalRank,trueRank, ...
                trueMode3Rank,r3);

            assert(trueTubalRank==trueRank, ...
                'Generated L0 has incorrect tubal rank.');
            assert(trueMode3Rank==r3, ...
                'Generated L0 has incorrect mode-3 rank.');

            %% ========================================================
            %% 1. LRTV
            %% ========================================================
            methodIdx = 1;

            % LRTV constrains the rank of the (n^2)-by-n mode-3 matrix,
            % hence its rank parameter is r3.
            tauLRTV = 0.005;
            lambdaLRTV = 5000/ sqrt(n*n);
            rankLRTV = r3;

            try
                tic;
                [Lhat, Ehat, ~] = LRTV_accelerate( ...
                    Y, tauLRTV, lambdaLRTV, rankLRTV);
                Runtime(methodIdx,caseIdx,trial) = toc;
                Iterations(methodIdx,caseIdx,trial) = NaN;

                [ErrL(methodIdx,caseIdx,trial), ...
                 ErrE(methodIdx,caseIdx,trial), ...
                 EstimatedTubalRank(methodIdx,caseIdx,trial), ...
                 EstimatedMode3Rank(methodIdx,caseIdx,trial), ...
                 EstimatedSparsity(methodIdx,caseIdx,trial)] = ...
                    evaluate_result(L0,E0,Lhat,Ehat,rankTol,sparseTol);

            catch ME
                warning('LRTV failed at case %d, trial %d: %s', ...
                    caseIdx,trial,ME.message);
            end

            %% ========================================================
            %% 2. ATNN
            %% ========================================================
            methodIdx = 2;

            optsATNN = struct();
            optsATNN.DEBUG = 0;
            optsATNN.lambda = 10 / sqrt(n);
            optsATNN.r = r3;
            optsATNN.rho = 1.05;
            optsATNN.tol = 1e-7;
            optsATNN.maxIter = 500;

            try
                tic;
                % Use the same global Frobenius normalization as AC^2-TRPCA.
                % All ATNN parameters remain unchanged.
                [Lhat,Ehat,Iterations(methodIdx,caseIdx,trial)] = ...
                    run_atnn_scaled(Y,optsATNN);
                Runtime(methodIdx,caseIdx,trial) = toc;

                [ErrL(methodIdx,caseIdx,trial), ...
                 ErrE(methodIdx,caseIdx,trial), ...
                 EstimatedTubalRank(methodIdx,caseIdx,trial), ...
                 EstimatedMode3Rank(methodIdx,caseIdx,trial), ...
                 EstimatedSparsity(methodIdx,caseIdx,trial)] = ...
                    evaluate_result(L0,E0,Lhat,Ehat,rankTol,sparseTol);

            catch ME
                warning('ATNN failed at case %d, trial %d: %s', ...
                    caseIdx,trial,ME.message);
            end

            %% ========================================================
            %% 3. CCSVS
            %% ========================================================
            methodIdx = 3;

            optsCCSVS = struct();
            optsCCSVS.tol = 1e-7;
            optsCCSVS.mu = 1e-4;
            optsCCSVS.rho = 1.1;
            optsCCSVS.max_iter = 500;
            optsCCSVS.DEBUG = 0;

            ll = n;
            Pccsvs = 2;

            optsCCSVS.w = [ ...
                linspace(1e-5,1e-7,Pccsvs)'; ...
                0.7 * ones(ll-Pccsvs,1)];

            optsCCSVS.P = Pccsvs;
            optsCCSVS.Slice_weights = [ ...
                0.55, 1.55 * ones(1,n-1)];

            lambdaCCSVS = 1 / sqrt(n * n);

            try
                tic;
                % Use the original CCSVS synthetic-experiment scale.
                % Do not apply the AC2-specific global normalization here.
                [Lhat,Ehat] = trpca_tnn( ...
                    Y,lambdaCCSVS,optsCCSVS);
                Runtime(methodIdx,caseIdx,trial) = toc;
                Iterations(methodIdx,caseIdx,trial) = NaN;

                [ErrL(methodIdx,caseIdx,trial), ...
                 ErrE(methodIdx,caseIdx,trial), ...
                 EstimatedTubalRank(methodIdx,caseIdx,trial), ...
                 EstimatedMode3Rank(methodIdx,caseIdx,trial), ...
                 EstimatedSparsity(methodIdx,caseIdx,trial)] = ...
                    evaluate_result(L0,E0,Lhat,Ehat,rankTol,sparseTol);

            catch ME
                warning('CCSVS failed at case %d, trial %d: %s', ...
                    caseIdx,trial,ME.message);
            end

            %% ========================================================
            %% 4. AC^2-TRPCA: preserve the user's original solver
            %% ========================================================
            methodIdx = 4;

            optsAC2 = struct();
            optsAC2.r = r3;
            % Fixed global rule; no access to the unknown true rank.
            optsAC2.P = ceil(0.1 * min(n,n));
            optsAC2.lambda = 1 / sqrt(n);
            optsAC2.tol = 1e-7;
            optsAC2.maxIter = 500;

            try
                tic;
                [Lhat,Ehat,Iterations(methodIdx,caseIdx,trial)] = ...
                    AC2_TRPCA_Solver_Robust(Y,optsAC2);
                Runtime(methodIdx,caseIdx,trial) = toc;

                [ErrL(methodIdx,caseIdx,trial), ...
                 ErrE(methodIdx,caseIdx,trial), ...
                 EstimatedTubalRank(methodIdx,caseIdx,trial), ...
                 EstimatedMode3Rank(methodIdx,caseIdx,trial), ...
                 EstimatedSparsity(methodIdx,caseIdx,trial)] = ...
                    evaluate_result(L0,E0,Lhat,Ehat,rankTol,sparseTol);

            catch ME
                warning('AC^2-TRPCA failed at case %d, trial %d: %s', ...
                    caseIdx,trial,ME.message);
            end

            %% ---------- Success indicator ----------
            for methodIdx = 1:numMethods
                Success(methodIdx,caseIdx,trial) = ...
                    isfinite(ErrL(methodIdx,caseIdx,trial)) && ...
                    isfinite(ErrE(methodIdx,caseIdx,trial)) && ...
                    max(ErrL(methodIdx,caseIdx,trial), ...
                        ErrE(methodIdx,caseIdx,trial)) < successTol;
            end

            %% ---------- Console display ----------
            fprintf('\n%-18s %9s %9s %12s %14s %14s %10s\n', ...
                'Method','rank_t','rank_3','||Ehat||_0', ...
                'RelErr(L)','RelErr(E)','Time(s)');

            for methodIdx = 1:numMethods
                fprintf('%-18s %9.0f %9.0f %12.0f %14.3e %14.3e %10.3f\n', ...
                    methodNames{methodIdx}, ...
                    EstimatedTubalRank(methodIdx,caseIdx,trial), ...
                    EstimatedMode3Rank(methodIdx,caseIdx,trial), ...
                    EstimatedSparsity(methodIdx,caseIdx,trial), ...
                    ErrL(methodIdx,caseIdx,trial), ...
                    ErrE(methodIdx,caseIdx,trial), ...
                    Runtime(methodIdx,caseIdx,trial));
            end

            clear D0 B0 L0 E0 Y Lhat Ehat index;
        end
    end
end

%% ==================== Detailed table ====================
NColumn = [];
R3Column = [];
SparseRatioColumn = [];
TrueSparsityColumn = [];
MethodColumn = cell(0,1);
EstimatedTubalRankColumn = [];
EstimatedMode3RankColumn = [];
EstimatedSparsityColumn = [];
ErrLColumn = [];
ErrEColumn = [];
TimeColumn = [];
IterationsColumn = [];
TrialColumn = [];
SuccessColumn = [];

for c = 1:numCases
    for trial = 1:numTrials
        for methodIdx = 1:numMethods

            NColumn(end+1,1) = CaseN(c); %#ok<SAGROW>
            R3Column(end+1,1) = CaseR3(c); %#ok<SAGROW>
            SparseRatioColumn(end+1,1) = CaseSparseRatio(c); %#ok<SAGROW>
            TrueSparsityColumn(end+1,1) = CaseTrueSparsity(c); %#ok<SAGROW>
            MethodColumn{end+1,1} = methodNames{methodIdx}; %#ok<SAGROW>

            EstimatedTubalRankColumn(end+1,1) = ...
                EstimatedTubalRank(methodIdx,c,trial); %#ok<SAGROW>
            EstimatedMode3RankColumn(end+1,1) = ...
                EstimatedMode3Rank(methodIdx,c,trial); %#ok<SAGROW>
            EstimatedSparsityColumn(end+1,1) = ...
                EstimatedSparsity(methodIdx,c,trial); %#ok<SAGROW>
            ErrLColumn(end+1,1) = ErrL(methodIdx,c,trial); %#ok<SAGROW>
            ErrEColumn(end+1,1) = ErrE(methodIdx,c,trial); %#ok<SAGROW>
            TimeColumn(end+1,1) = Runtime(methodIdx,c,trial); %#ok<SAGROW>
            IterationsColumn(end+1,1) = ...
                Iterations(methodIdx,c,trial); %#ok<SAGROW>
            TrialColumn(end+1,1) = trial; %#ok<SAGROW>
            SuccessColumn(end+1,1) = Success(methodIdx,c,trial); %#ok<SAGROW>
        end
    end
end

DetailedTable = table( ...
    NColumn,R3Column,SparseRatioColumn,TrueSparsityColumn, ...
    MethodColumn,EstimatedTubalRankColumn,EstimatedMode3RankColumn, ...
    EstimatedSparsityColumn,ErrLColumn,ErrEColumn,TimeColumn,IterationsColumn, ...
    TrialColumn,SuccessColumn, ...
    'VariableNames',{ ...
    'n','True_Tubal_Rank','Sparse_Ratio','True_Sparsity','Method', ...
    'Estimated_Tubal_Rank','Estimated_Mode3_Rank','Estimated_Sparsity', ...
    'Relative_Error_L','Relative_Error_E','Time_s', ...
    'Iterations','Trial','Success'});

disp('================ Detailed synthetic comparison ================');
disp(DetailedTable);

writetable(DetailedTable, ...
    fullfile(saveRoad,'Table1_AllMethods_Detailed.csv'));

%% ==================== Mean +/- std table ====================
MeanTubalRank = mean(EstimatedTubalRank,3,'omitnan');
MeanMode3Rank = mean(EstimatedMode3Rank,3,'omitnan');
MeanSparsity = mean(EstimatedSparsity,3,'omitnan');

MeanErrL = mean(ErrL,3,'omitnan');
StdErrL = std(ErrL,0,3,'omitnan');

MeanErrE = mean(ErrE,3,'omitnan');
StdErrE = std(ErrE,0,3,'omitnan');

MeanTime = mean(Runtime,3,'omitnan');
StdTime = std(Runtime,0,3,'omitnan');

MeanIterations = mean(Iterations,3,'omitnan');
SuccessRate = mean(Success,3);

SummaryN = [];
SummaryR3 = [];
SummarySparseRatio = [];
SummaryTrueSparsity = [];
SummaryMethod = cell(0,1);
SummaryMeanTubalRank = [];
SummaryMeanMode3Rank = [];
SummaryMeanSparsity = [];
SummaryMeanErrL = [];
SummaryStdErrL = [];
SummaryMeanErrE = [];
SummaryStdErrE = [];
SummaryMeanTime = [];
SummaryStdTime = [];
SummaryMeanIterations = [];
SummarySuccessRate = [];

for c = 1:numCases
    for methodIdx = 1:numMethods

        SummaryN(end+1,1) = CaseN(c); %#ok<SAGROW>
        SummaryR3(end+1,1) = CaseR3(c); %#ok<SAGROW>
        SummarySparseRatio(end+1,1) = CaseSparseRatio(c); %#ok<SAGROW>
        SummaryTrueSparsity(end+1,1) = CaseTrueSparsity(c); %#ok<SAGROW>
        SummaryMethod{end+1,1} = methodNames{methodIdx}; %#ok<SAGROW>

        SummaryMeanTubalRank(end+1,1) = ...
            MeanTubalRank(methodIdx,c); %#ok<SAGROW>
        SummaryMeanMode3Rank(end+1,1) = ...
            MeanMode3Rank(methodIdx,c); %#ok<SAGROW>
        SummaryMeanSparsity(end+1,1) = ...
            MeanSparsity(methodIdx,c); %#ok<SAGROW>
        SummaryMeanErrL(end+1,1) = MeanErrL(methodIdx,c); %#ok<SAGROW>
        SummaryStdErrL(end+1,1) = StdErrL(methodIdx,c); %#ok<SAGROW>
        SummaryMeanErrE(end+1,1) = MeanErrE(methodIdx,c); %#ok<SAGROW>
        SummaryStdErrE(end+1,1) = StdErrE(methodIdx,c); %#ok<SAGROW>
        SummaryMeanTime(end+1,1) = MeanTime(methodIdx,c); %#ok<SAGROW>
        SummaryStdTime(end+1,1) = StdTime(methodIdx,c); %#ok<SAGROW>
        SummaryMeanIterations(end+1,1) = ...
            MeanIterations(methodIdx,c); %#ok<SAGROW>
        SummarySuccessRate(end+1,1) = ...
            SuccessRate(methodIdx,c); %#ok<SAGROW>
    end
end

SummaryTable = table( ...
    SummaryN,SummaryR3,SummarySparseRatio,SummaryTrueSparsity, ...
    SummaryMethod,SummaryMeanTubalRank,SummaryMeanMode3Rank, ...
    SummaryMeanSparsity, ...
    SummaryMeanErrL,SummaryStdErrL, ...
    SummaryMeanErrE,SummaryStdErrE, ...
    SummaryMeanTime,SummaryStdTime, ...
    SummaryMeanIterations,SummarySuccessRate, ...
    'VariableNames',{ ...
    'n','True_Tubal_Rank','Sparse_Ratio','True_Sparsity','Method', ...
    'Mean_Estimated_Tubal_Rank','Mean_Estimated_Mode3_Rank', ...
    'Mean_Estimated_Sparsity', ...
    'Mean_Relative_Error_L','Std_Relative_Error_L', ...
    'Mean_Relative_Error_E','Std_Relative_Error_E', ...
    'Mean_Time_s','Std_Time_s', ...
    'Mean_Iterations','Success_Rate'});

disp('================ Mean/std synthetic comparison ================');
disp(SummaryTable);

writetable(SummaryTable, ...
    fullfile(saveRoad,'Table1_AllMethods_MeanStd.csv'));

%% ==================== Compact manuscript table ====================
% The compact table follows the structure:
% Problem settings | Method | Estimated results | Relative errors
%
% Because three trials are used:
%   - estimated ranks and sparsities are reported by their median;
%   - relative errors are reported by their mean.
% Full standard deviations remain available in SummaryTable.

MedianTubalRank = median(EstimatedTubalRank,3,'omitnan');
MedianSparsity = median(EstimatedSparsity,3,'omitnan');

numCompactRows = numCases * numMethods;

CompactN = strings(numCompactRows,1);
CompactTrueRank = strings(numCompactRows,1);
CompactTrueSparsity = strings(numCompactRows,1);
CompactMethod = strings(numCompactRows,1);
CompactEstimatedRank = strings(numCompactRows,1);
CompactEstimatedSparsity = strings(numCompactRows,1);
CompactErrL = strings(numCompactRows,1);
CompactErrE = strings(numCompactRows,1);

row = 0;
for c = 1:numCases
    for methodIdx = 1:numMethods
        row = row + 1;

        % Leave repeated problem-setting cells blank after the first method
        % so the exported table visually matches a grouped manuscript table.
        if methodIdx == 1
            CompactN(row) = sprintf('%d',CaseN(c));
            CompactTrueRank(row) = sprintf('%d',CaseR3(c));
            CompactTrueSparsity(row) = sprintf('%d',CaseTrueSparsity(c));
        else
            CompactN(row) = "";
            CompactTrueRank(row) = "";
            CompactTrueSparsity(row) = "";
        end

        CompactMethod(row) = string(methodNames{methodIdx});
        CompactEstimatedRank(row) = sprintf('%.0f', ...
            MedianTubalRank(methodIdx,c));
        CompactEstimatedSparsity(row) = sprintf('%.0f', ...
            MedianSparsity(methodIdx,c));
        CompactErrL(row) = sprintf('%.2e',MeanErrL(methodIdx,c));
        CompactErrE(row) = sprintf('%.2e',MeanErrE(methodIdx,c));
    end
end

CompactTable = table( ...
    CompactN,CompactTrueRank,CompactTrueSparsity,CompactMethod, ...
    CompactEstimatedRank,CompactEstimatedSparsity, ...
    CompactErrL,CompactErrE, ...
    'VariableNames',{ ...
    'n','rank_t_T0','norm_E0_0','Method', ...
    'rank_t_That','norm_Ehat_0', ...
    'Relative_Error_L','Relative_Error_E'});

disp('================ Compact manuscript table ================');
disp(CompactTable);

writetable(CompactTable, ...
    fullfile(saveRoad,'Table1_Compact_Manuscript.csv'));

save(fullfile(saveRoad,'Table1_AllMethods_All.mat'), ...
    'n_list','configs','numTrials','methodNames', ...
    'CaseN','CaseR3','CaseSparseRatio','CaseTrueSparsity', ...
    'ErrL','ErrE','EstimatedTubalRank','EstimatedMode3Rank','EstimatedSparsity', ...
    'Runtime','Iterations','Success', ...
    'DetailedTable','SummaryTable','CompactTable');

fprintf('\nAll results saved to:\n%s\n',saveRoad);

%% ========================================================================
%% Local function: mode-3 product
%% ========================================================================
function T = mode3_product(B,D)

[n1,n2,r3] = size(B);
[n3,r3D] = size(D);

assert(r3==r3D, ...
    'Third dimension of B must equal the number of columns of D.');

B3 = reshape(permute(B,[3,1,2]),r3,[]);
T3 = D * B3;
T = ipermute(reshape(T3,[n3,n1,n2]),[3,1,2]);
end

%% ========================================================================
%% Local function: evaluate result
%% ========================================================================
function [errL,errE,tubalRankEst,mode3RankEst,sparseEst] = ...
    evaluate_result(L0,E0,Lhat,Ehat,rankTol,sparseTol)

Lhat = real(Lhat);
Ehat = real(Ehat);

errL = norm(Lhat(:)-L0(:)) / max(norm(L0(:)),eps);
errE = norm(Ehat(:)-E0(:)) / max(norm(E0(:)),eps);

tubalRankEst = numerical_tubal_rank(Lhat,rankTol);
mode3RankEst = numerical_mode3_rank(Lhat,rankTol);
sparseEst = nnz(abs(Ehat(:))>sparseTol);
end

%% ========================================================================
%% Local function: numerical mode-3 rank
%% ========================================================================
function r = numerical_mode3_rank(T,relativeTol)

[n1,n2,n3] = size(T);
T3 = reshape(T,n1*n2,n3);

s = svd(T3,'econ');

if isempty(s) || s(1)==0
    r = 0;
else
    r = sum(s > relativeTol*s(1));
end
end

%% ========================================================================
%% Fair generator: low tubal rank and low mode-3 rank simultaneously
%% ========================================================================
function [L0,B0,D0] = generate_joint_lowrank_tensor(n,r3,R)
% All core frontal slices share the same spatial column/row subspaces:
%       B0(:,:,k) = U*C_k*V'.
% Hence every Fourier slice of B0 and every Fourier slice of
% L0=B0 x_3 D0 has rank at most R. Random full-rank C_k make the tubal
% rank equal to R with probability one.

assert(r3 <= R^2, ...
    'Need r3 <= R^2 to obtain r3 independent coefficient matrices.');

[U,~] = qr(randn(n,R),0);
[V,~] = qr(randn(n,R),0);
[D0,~] = qr(randn(n,r3),0);

B0 = zeros(n,n,r3);

for k = 1:r3
    Ck = randn(R,R) + 2*eye(R);
    B0(:,:,k) = U*Ck*V';
end

L0 = mode3_product(B0,D0);
end

%% ========================================================================
%% Numerical tubal rank with one global threshold
%% ========================================================================
function r = numerical_tubal_rank(T,relativeTol)

Tf = fft(T,[],3);
n3 = size(Tf,3);
sAll = cell(n3,1);
globalMax = 0;

for k = 1:n3
    s = svd(Tf(:,:,k),'econ');
    sAll{k} = s;
    if ~isempty(s)
        globalMax = max(globalMax,s(1));
    end
end

if globalMax==0
    r = 0;
    return;
end

threshold = relativeTol * globalMax;
r = 0;

for k = 1:n3
    r = max(r,sum(sAll{k}>threshold));
end
end

%% ========================================================================
%% LRTV wrapper with the same global normalization used by AC^2-TRPCA
%% ========================================================================
function [L,E,N] = run_lrtv_scaled(Y,tau,lambda,r)

scale = norm(Y(:));
Yn = Y / max(scale,eps);

[Ln,En,Nn] = LRTV_accelerate(Yn,tau,lambda,r);

L = Ln * scale;
E = En * scale;
N = Nn * scale;
end

%% ========================================================================
%% ATNN wrapper with common global normalization
%% ========================================================================
function [L,E,iter] = run_atnn_scaled(Y,opts)

scale = norm(Y(:));
Yn = Y / max(scale,eps);

[Ln,En,iter] = ATNN_RPCA_unifiedstop(Yn,opts);

L = Ln * scale;
E = En * scale;
end

%% ========================================================================
%% CCSVS wrapper with common global normalization
%% ========================================================================
function [L,E] = run_ccsvs_scaled(Y,lambda,opts)

scale = norm(Y(:));
Yn = Y / max(scale,eps);

[Ln,En] = trpca_tnn(Yn,lambda,opts);

L = Ln * scale;
E = En * scale;
end

%% ========================================================================
%% User's AC^2-TRPCA solver
%% ========================================================================
function [L,E,iter] = AC2_TRPCA_Solver_Robust(Y,opts)

[n1,n2,n3] = size(Y);

% 1. Global normalization.
scale = norm(Y(:));
Y = Y / max(scale,eps);

% 2. Spectral initialization.
Ymat = reshape(Y,[],n3);
[~,~,Vinit] = svd(Ymat,'econ');
D = Vinit(:,1:opts.r);

B = mode3_project_local(Y,D);

E = zeros(size(Y));
M = zeros(size(Y));

mu = 1e-3;
maxMu = 1e8;
rho = 1.1;

P = opts.P;
lambda = opts.lambda;

% 3. Iterations.
for iter = 1:opts.maxIter

    % Update B.
    Temp = Y - E + M/mu;
    Ntensor = mode3_project_local(Temp,D);
    B = prox_tnnsep_robust(Ntensor,1/mu,P);

    % Update D by orthogonal Procrustes.
    Temp3 = reshape(permute(Temp,[3,1,2]),n3,[]);
    B3 = reshape(permute(B,[3,1,2]),opts.r,[]);

    MatForD = Temp3 * B3';

    [Ud,~,Vd] = svd(MatForD,'econ');
    D = Ud * Vd';

    % Update E.
    L = mode3_product(B,D);

    Residual = Y - L + M/mu;
    threshold = lambda/mu;
    E = sign(Residual) .* max(abs(Residual)-threshold,0);

    % Update multiplier.
    Z = Y - L - E;
    M = M + mu*Z;
    mu = min(mu*rho,maxMu);

    if norm(Z(:)) < opts.tol
        break;
    end
end

% 4. Rescale.
L = L * scale;
E = E * scale;
end


function B = mode3_project_local(T,D)

[n1,n2,n3] = size(T);
r3 = size(D,2);

T3 = reshape(permute(T,[3,1,2]),n3,[]);
B3 = D' * T3;
B = ipermute(reshape(B3,[r3,n1,n2]),[3,1,2]);
end

function X = prox_tnnsep_robust(Y,tau,P)

[~,~,r3] = size(Y);

Yhat = fft(Y,[],3);
Xhat = zeros(size(Yhat));

wShrink = 1.0;

for i = 1:r3

    [U,S,V] = svd(Yhat(:,:,i),'econ');
    s = diag(S);
    sNew = zeros(size(s));

    protectedCount = min(P,numel(s));

    if protectedCount > 0
        sNew(1:protectedCount) = s(1:protectedCount);
    end

    if protectedCount < numel(s)
        sNew(protectedCount+1:end) = max( ...
            s(protectedCount+1:end)-tau*wShrink,0);
    end

    Xhat(:,:,i) = U * diag(sNew) * V';
end

X = real(ifft(Xhat,[],3));
end
